---

docker_version: "1.13.1"
docker_package_file: "docker-{{ docker_version }}.tgz"
docker_download_url: "https://get.docker.com/builds/Linux/x86_64/{{ docker_package_file }}"
cni_package_file: "cni-plugins-amd64-v0.6.0.tgz"
cni_download_url: "https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz"
kubernetes_version: "v1.7.4"
kubelet_download_path: "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version }}/bin/linux/amd64"
